data:
  datasets_path: "/Users/aurorastudyvn/Workspace/ML/flowers_detection/datasets/raw"
  is_own_dataset: false
  image_size: [200, 200]
  batch_size: 32
  test_split: 0.2
  validation_split: 0.2
  image_per_class: 120
  is_cache: true

model:
  input_shape: [200, 200, 3]
  num_classes: 10
  base_model_name: "ResNet50"
  dropout_rate: 0.3
  learning_rate: 0.001

training:
  is_cache: true
  epochs: 30
  early_stopping_patience: 5
  checkpoint_path: "saved/model.keras"
  tensorboard_log_dir: "logs/"

augmentation:
  horizontal_flip: true
  vertical_flip: true
  rotation_range: 0.4
  zoom_range: 0.2
  contrast_range: 0.2
  brightness_range: 0.2
  translation_range: [0.2, 0.2]

classes:
  - "Hoàng Hậu"
  - "Trang"
  - "Trang Trắng"
  - "Dừa Cạn"
  - "Cúc"
  - "Giấy"
  - "Đại Tướng Quân"
  - "Lan"
  - "Loa Kèn"
  - "Bằng Lăng"
